name: autogen_qa_sweeps
method: random

# Metric to optimize. This is just an example, modify as per your needs.
metric:
  name: f1
  goal: maximize

parameters:
  dotenv_path: 
    values: ['../../.env']
  temperature:
    values: [0.1, 0.5, 0.7]
  llm:
    values:
      - gpt-4
      - gpt-3.5-turbo
