name: autogen_qa_sweeps
method: random

# Metric to optimize. This is just an example, modify as per your needs.
metric:
  name: accuracy
  goal: maximize

parameters:
  temperature:
    min: 0.5
    max: 1.0
  num_qa_pairs:
    values: [3, 5, 7, 10]
  llm:
    values:
      - gpt-4
      - gpt-3.5-turbo

# Additional Parameters (Not for WandB sweep but may be used in your code)
additional_params:
  temperature: 0.7
  num_qa_pairs: 5 # number of questions
  llm:
    values:
      - gpt-4
      - gpt-3.5-turbo
  # prompt_template_file:
  #   values:
  #     - data/qa/prompt_template_1.txt
  #     - data/qa/prompt_template_2.txt
  # retriever:
  #   values:
  #     - Chroma
  #     - TFIDFRetriever
  #     - FAISS
# program: qa_full_sweeps.py