job: extension
config:
  name: pollock_lora
  process:
  - type: sd_trainer
    training_folder: ../../output_lora
    device: mps
    trigger_word: pollockdrip
    network:
      type: lora
      linear: 32
      linear_alpha: 32
    save:
      dtype: float16
      save_every: 250
      max_step_saves_to_keep: 4
      push_to_hub: false
    datasets:
    - folder_path: ../../img
      caption_ext: txt
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: false
      resolution:
      - 1024
    train:
      batch_size: 1
      steps: 1040
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0004
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
    model:
      name_or_path: black-forest-labs/FLUX.1-dev
      is_flux: true
      quantize: false
    sample:
      sampler: flowmatch
      sample_every: 250
      width: 1024
      height: 1024
      prompts:
      - '[trigger], abstract expressionist painting with energetic black and white
        drips over a beige canvas'
      - '[trigger], chaotic layered drips with red and yellow paint splatters'
      - '[trigger], large scale canvas with dense paint trails and overlapping textures'
      - '[trigger], fluid motion in paint, non-representational style, layered paint
        buildup'
      - '[trigger], expressive splatter technique, ink and acrylic mix, muted tones'
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 3
      sample_steps: 20
meta:
  name: pollock_lora
  version: '1.0'
