# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(950, 620)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(950, 620))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 950, 600))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_read = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_read.setGeometry(QtCore.QRect(250, 490, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_read.setFont(font)
        self.pushButton_read.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_read.setObjectName("pushButton_read")
        self.pushButton_set = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_set.setGeometry(QtCore.QRect(440, 490, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_set.setFont(font)
        self.pushButton_set.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_set.setObjectName("pushButton_set")
        self.pushButton_default = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_default.setGeometry(QtCore.QRect(620, 490, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_default.setFont(font)
        self.pushButton_default.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_default.setObjectName("pushButton_default")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(350, 90, 220, 160))
        self.widget.setStyleSheet("#widget {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget.setObjectName("widget")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(80, 10, 64, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalSlider_servoMin = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_servoMin.setGeometry(QtCore.QRect(30, 60, 160, 22))
        self.horizontalSlider_servoMin.setMaximum(1000)
        self.horizontalSlider_servoMin.setPageStep(1)
        self.horizontalSlider_servoMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMin.setObjectName("horizontalSlider_servoMin")
        self.horizontalSlider_servoMax = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_servoMax.setGeometry(QtCore.QRect(30, 120, 160, 22))
        self.horizontalSlider_servoMax.setMinimum(0)
        self.horizontalSlider_servoMax.setMaximum(1000)
        self.horizontalSlider_servoMax.setPageStep(1)
        self.horizontalSlider_servoMax.setProperty("value", 1000)
        self.horizontalSlider_servoMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMax.setObjectName("horizontalSlider_servoMax")
        self.label_servoMin = QtWidgets.QLabel(self.widget)
        self.label_servoMin.setGeometry(QtCore.QRect(15, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMin.setFont(font)
        self.label_servoMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMin.setObjectName("label_servoMin")
        self.label_servoMax = QtWidgets.QLabel(self.widget)
        self.label_servoMax.setGeometry(QtCore.QRect(160, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMax.setFont(font)
        self.label_servoMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMax.setObjectName("label_servoMax")
        self.widget_6 = QtWidgets.QWidget(self.tab_2)
        self.widget_6.setGeometry(QtCore.QRect(350, 280, 220, 160))
        self.widget_6.setStyleSheet("#widget_6 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_6.setObjectName("widget_6")
        self.label_19 = QtWidgets.QLabel(self.widget_6)
        self.label_19.setGeometry(QtCore.QRect(80, 10, 64, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalSlider_servoMinV = QtWidgets.QSlider(self.widget_6)
        self.horizontalSlider_servoMinV.setGeometry(QtCore.QRect(30, 60, 160, 22))
        self.horizontalSlider_servoMinV.setMinimum(45)
        self.horizontalSlider_servoMinV.setMaximum(140)
        self.horizontalSlider_servoMinV.setPageStep(1)
        self.horizontalSlider_servoMinV.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMinV.setObjectName("horizontalSlider_servoMinV")
        self.horizontalSlider_servoMaxV = QtWidgets.QSlider(self.widget_6)
        self.horizontalSlider_servoMaxV.setGeometry(QtCore.QRect(30, 120, 160, 22))
        self.horizontalSlider_servoMaxV.setMinimum(45)
        self.horizontalSlider_servoMaxV.setMaximum(140)
        self.horizontalSlider_servoMaxV.setPageStep(1)
        self.horizontalSlider_servoMaxV.setProperty("value", 140)
        self.horizontalSlider_servoMaxV.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMaxV.setObjectName("horizontalSlider_servoMaxV")
        self.label_servoMinV = QtWidgets.QLabel(self.widget_6)
        self.label_servoMinV.setGeometry(QtCore.QRect(20, 30, 50, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMinV.setFont(font)
        self.label_servoMinV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMinV.setObjectName("label_servoMinV")
        self.label_servoMaxV = QtWidgets.QLabel(self.widget_6)
        self.label_servoMaxV.setGeometry(QtCore.QRect(150, 90, 50, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMaxV.setFont(font)
        self.label_servoMaxV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMaxV.setObjectName("label_servoMaxV")
        self.widget_7 = QtWidgets.QWidget(self.tab_2)
        self.widget_7.setGeometry(QtCore.QRect(60, 350, 220, 90))
        self.widget_7.setStyleSheet("#widget_7 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalSlider_servoTemp = QtWidgets.QSlider(self.widget_7)
        self.horizontalSlider_servoTemp.setGeometry(QtCore.QRect(50, 50, 160, 22))
        self.horizontalSlider_servoTemp.setMinimum(50)
        self.horizontalSlider_servoTemp.setMaximum(100)
        self.horizontalSlider_servoTemp.setPageStep(1)
        self.horizontalSlider_servoTemp.setProperty("value", 85)
        self.horizontalSlider_servoTemp.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoTemp.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_servoTemp.setObjectName("horizontalSlider_servoTemp")
        self.label_20 = QtWidgets.QLabel(self.widget_7)
        self.label_20.setGeometry(QtCore.QRect(70, 10, 91, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_servoTemp = QtWidgets.QLabel(self.widget_7)
        self.label_servoTemp.setGeometry(QtCore.QRect(4, 45, 45, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoTemp.setFont(font)
        self.label_servoTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoTemp.setObjectName("label_servoTemp")
        self.widget_8 = QtWidgets.QWidget(self.tab_2)
        self.widget_8.setGeometry(QtCore.QRect(650, 90, 240, 180))
        self.widget_8.setStyleSheet("#widget_8 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_8.setObjectName("widget_8")
        self.label_21 = QtWidgets.QLabel(self.widget_8)
        self.label_21.setGeometry(QtCore.QRect(15, 30, 151, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_8)
        self.label_22.setGeometry(QtCore.QRect(15, 130, 171, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_8)
        self.label_23.setGeometry(QtCore.QRect(15, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_servoCurrentP = QtWidgets.QLabel(self.widget_8)
        self.label_servoCurrentP.setGeometry(QtCore.QRect(170, 25, 50, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoCurrentP.setFont(font)
        self.label_servoCurrentP.setText("")
        self.label_servoCurrentP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoCurrentP.setObjectName("label_servoCurrentP")
        self.label_servoCurrentV = QtWidgets.QLabel(self.widget_8)
        self.label_servoCurrentV.setGeometry(QtCore.QRect(160, 75, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoCurrentV.setFont(font)
        self.label_servoCurrentV.setText("")
        self.label_servoCurrentV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoCurrentV.setObjectName("label_servoCurrentV")
        self.label_servoCurrentTemp = QtWidgets.QLabel(self.widget_8)
        self.label_servoCurrentTemp.setGeometry(QtCore.QRect(180, 125, 50, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoCurrentTemp.setFont(font)
        self.label_servoCurrentTemp.setText("")
        self.label_servoCurrentTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoCurrentTemp.setObjectName("label_servoCurrentTemp")
        self.widget_9 = QtWidgets.QWidget(self.tab_2)
        self.widget_9.setGeometry(QtCore.QRect(60, 90, 220, 80))
        self.widget_9.setStyleSheet("#widget_9 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_9.setObjectName("widget_9")
        self.label_11 = QtWidgets.QLabel(self.widget_9)
        self.label_11.setGeometry(QtCore.QRect(80, 5, 48, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_servoID = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_servoID.setGeometry(QtCore.QRect(75, 40, 91, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit_servoID.setFont(font)
        self.lineEdit_servoID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_servoID.setObjectName("lineEdit_servoID")
        self.label_32 = QtWidgets.QLabel(self.widget_9)
        self.label_32.setGeometry(QtCore.QRect(20, 40, 48, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.widget_10 = QtWidgets.QWidget(self.tab_2)
        self.widget_10.setGeometry(QtCore.QRect(60, 220, 220, 80))
        self.widget_10.setStyleSheet("#widget_10 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_10.setObjectName("widget_10")
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setGeometry(QtCore.QRect(75, 5, 81, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_servoDev = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_servoDev.setGeometry(QtCore.QRect(75, 40, 91, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit_servoDev.setFont(font)
        self.lineEdit_servoDev.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_servoDev.setObjectName("lineEdit_servoDev")
        self.label_24 = QtWidgets.QLabel(self.widget_10)
        self.label_24.setGeometry(QtCore.QRect(5, 40, 65, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.widget_11 = QtWidgets.QWidget(self.tab_2)
        self.widget_11.setGeometry(QtCore.QRect(650, 310, 240, 131))
        self.widget_11.setStyleSheet("#widget_11 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_11.setObjectName("widget_11")
        self.horizontalSlider_servoMove = QtWidgets.QSlider(self.widget_11)
        self.horizontalSlider_servoMove.setGeometry(QtCore.QRect(50, 50, 160, 22))
        self.horizontalSlider_servoMove.setMinimum(0)
        self.horizontalSlider_servoMove.setMaximum(1000)
        self.horizontalSlider_servoMove.setPageStep(1)
        self.horizontalSlider_servoMove.setProperty("value", 500)
        self.horizontalSlider_servoMove.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMove.setObjectName("horizontalSlider_servoMove")
        self.label_servoMove = QtWidgets.QLabel(self.widget_11)
        self.label_servoMove.setGeometry(QtCore.QRect(5, 45, 40, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMove.setFont(font)
        self.label_servoMove.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMove.setObjectName("label_servoMove")
        self.pushButton_resetPos = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_resetPos.setGeometry(QtCore.QRect(95, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_resetPos.setFont(font)
        self.pushButton_resetPos.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_resetPos.setObjectName("pushButton_resetPos")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(180, 20, 591, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BusServo 1.0"))
        self.pushButton_read.setText(_translate("Form", "Read"))
        self.pushButton_set.setText(_translate("Form", "Apply"))
        self.pushButton_default.setText(_translate("Form", "Default"))
        self.label_17.setText(_translate("Form", "Angle"))
        self.label_servoMin.setText(_translate("Form", "0"))
        self.label_servoMax.setText(_translate("Form", "1000"))
        self.label_19.setText(_translate("Form", "Voltage"))
        self.label_servoMinV.setText(_translate("Form", "4.5V"))
        self.label_servoMaxV.setText(_translate("Form", "14V"))
        self.label_20.setText(_translate("Form", "Temperature"))
        self.label_servoTemp.setText(_translate("Form", "85℃"))
        self.label_21.setText(_translate("Form", "Current Position："))
        self.label_22.setText(_translate("Form", "Current Temperature："))
        self.label_23.setText(_translate("Form", "Current Voltage："))
        self.label_11.setText(_translate("Form", "ID"))
        self.lineEdit_servoID.setText(_translate("Form", "1"))
        self.label_32.setText(_translate("Form", "ID"))
        self.label_14.setText(_translate("Form", "Deviation"))
        self.label_24.setText(_translate("Form", "-125~125"))
        self.label_servoMove.setText(_translate("Form", "500"))
        self.pushButton_resetPos.setText(_translate("Form", "ReSet"))
        self.label_36.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aa0000;\">Please note: before adjusting the servo, make sure that the controller is </span></p><p><span style=\" color:#aa0000;\">connected with only one servo, otherwise it may cause a conflicts!</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "BusServo Tool"))

