# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1660, 800)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1660, 800))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 10, 1658, 791))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(1425, 570, 231, 211))
        self.widget_5.setStyleSheet("#widget_5 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_5.setObjectName("widget_5")
        self.label_action = QtWidgets.QLabel(self.widget_5)
        self.label_action.setGeometry(QtCore.QRect(20, 20, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_action.setFont(font)
        self.label_action.setAlignment(QtCore.Qt.AlignCenter)
        self.label_action.setObjectName("label_action")
        self.comboBox_action = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_action.setGeometry(QtCore.QRect(110, 20, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_action.setFont(font)
        self.comboBox_action.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.comboBox_action.setObjectName("comboBox_action")
        self.Button_DelectSingle = QtWidgets.QPushButton(self.widget_5)
        self.Button_DelectSingle.setGeometry(QtCore.QRect(10, 80, 100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectSingle.setFont(font)
        self.Button_DelectSingle.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectSingle.setObjectName("Button_DelectSingle")
        self.Button_AllDelect = QtWidgets.QPushButton(self.widget_5)
        self.Button_AllDelect.setGeometry(QtCore.QRect(120, 80, 100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AllDelect.setFont(font)
        self.Button_AllDelect.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AllDelect.setObjectName("Button_AllDelect")
        self.Button_RunAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_RunAction.setGeometry(QtCore.QRect(10, 150, 100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_RunAction.setFont(font)
        self.Button_RunAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_RunAction.setObjectName("Button_RunAction")
        self.Button_StopAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_StopAction.setGeometry(QtCore.QRect(120, 150, 100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_StopAction.setFont(font)
        self.Button_StopAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_StopAction.setObjectName("Button_StopAction")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(1155, 570, 85, 211))
        self.widget_3.setStyleSheet("#widget_3 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_3.setObjectName("widget_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox.setGeometry(QtCore.QRect(13, 40, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Button_Run = QtWidgets.QPushButton(self.widget_3)
        self.Button_Run.setGeometry(QtCore.QRect(10, 100, 70, 81))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.Button_Run.setFont(font)
        self.Button_Run.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Run.setIconSize(QtCore.QSize(14, 14))
        self.Button_Run.setObjectName("Button_Run")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(980, 570, 171, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("#widget_2 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_2.setObjectName("widget_2")
        self.Button_ReadDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReadDeviation.setGeometry(QtCore.QRect(10, 15, 150, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReadDeviation.setFont(font)
        self.Button_ReadDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReadDeviation.setObjectName("Button_ReadDeviation")
        self.Button_DownloadDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_DownloadDeviation.setGeometry(QtCore.QRect(10, 80, 150, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DownloadDeviation.setFont(font)
        self.Button_DownloadDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DownloadDeviation.setObjectName("Button_DownloadDeviation")
        self.Button_ReSetServos = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReSetServos.setGeometry(QtCore.QRect(10, 145, 150, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReSetServos.setFont(font)
        self.Button_ReSetServos.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReSetServos.setObjectName("Button_ReSetServos")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(980, 0, 675, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);")
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(21)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(51)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget.verticalHeader().setMinimumSectionSize(22)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(1245, 570, 175, 211))
        self.widget_4.setStyleSheet("#widget_4 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_4.setObjectName("widget_4")
        self.Button_OpenActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_OpenActionGroup.setGeometry(QtCore.QRect(13, 15, 150, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_OpenActionGroup.setFont(font)
        self.Button_OpenActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_OpenActionGroup.setObjectName("Button_OpenActionGroup")
        self.Button_SaveActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_SaveActionGroup.setGeometry(QtCore.QRect(13, 80, 150, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_SaveActionGroup.setFont(font)
        self.Button_SaveActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_SaveActionGroup.setObjectName("Button_SaveActionGroup")
        self.Button_TandemActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_TandemActionGroup.setGeometry(QtCore.QRect(13, 145, 150, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_TandemActionGroup.setFont(font)
        self.Button_TandemActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_TandemActionGroup.setObjectName("Button_TandemActionGroup")
        self.widget_1 = QtWidgets.QWidget(self.widget)
        self.widget_1.setGeometry(QtCore.QRect(980, 450, 675, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.widget_1.setFont(font)
        self.widget_1.setStyleSheet("#widget_1 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_1.setObjectName("widget_1")
        self.label_time = QtWidgets.QLabel(self.widget_1)
        self.label_time.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.lineEdit_time = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_time.setGeometry(QtCore.QRect(80, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_time.setFont(font)
        self.lineEdit_time.setMaxLength(30000)
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.Button_AddAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_AddAction.setGeometry(QtCore.QRect(320, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AddAction.setFont(font)
        self.Button_AddAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AddAction.setObjectName("Button_AddAction")
        self.Button_DelectAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_DelectAction.setGeometry(QtCore.QRect(320, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectAction.setFont(font)
        self.Button_DelectAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectAction.setObjectName("Button_DelectAction")
        self.Button_UpdateAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_UpdateAction.setGeometry(QtCore.QRect(440, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_UpdateAction.setFont(font)
        self.Button_UpdateAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_UpdateAction.setObjectName("Button_UpdateAction")
        self.Button_InsertAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_InsertAction.setGeometry(QtCore.QRect(440, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_InsertAction.setFont(font)
        self.Button_InsertAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_InsertAction.setObjectName("Button_InsertAction")
        self.Button_ServoPowerDown = QtWidgets.QPushButton(self.widget_1)
        self.Button_ServoPowerDown.setGeometry(QtCore.QRect(200, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ServoPowerDown.setFont(font)
        self.Button_ServoPowerDown.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ServoPowerDown.setObjectName("Button_ServoPowerDown")
        self.Button_AngularReadback = QtWidgets.QPushButton(self.widget_1)
        self.Button_AngularReadback.setGeometry(QtCore.QRect(200, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AngularReadback.setFont(font)
        self.Button_AngularReadback.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AngularReadback.setObjectName("Button_AngularReadback")
        self.Button_MoveUpAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveUpAction.setGeometry(QtCore.QRect(560, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_MoveUpAction.setFont(font)
        self.Button_MoveUpAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveUpAction.setObjectName("Button_MoveUpAction")
        self.Button_MoveDownAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveDownAction.setGeometry(QtCore.QRect(560, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_MoveDownAction.setFont(font)
        self.Button_MoveDownAction.setStyleSheet("QPushButton{background-color: rgb(255, 170, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveDownAction.setObjectName("Button_MoveDownAction")
        self.label_total_time = QtWidgets.QLabel(self.widget_1)
        self.label_total_time.setGeometry(QtCore.QRect(6, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.label_total_time.setFont(font)
        self.label_total_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_time.setObjectName("label_total_time")
        self.label = QtWidgets.QLabel(self.widget_1)
        self.label.setGeometry(QtCore.QRect(150, 25, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        self.label_5.setGeometry(QtCore.QRect(170, 75, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_TotalTime = QtWidgets.QLabel(self.widget_1)
        self.label_TotalTime.setGeometry(QtCore.QRect(120, 77, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.label_TotalTime.setFont(font)
        self.label_TotalTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TotalTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TotalTime.setObjectName("label_TotalTime")
        self.checkBox_time = QtWidgets.QCheckBox(self.widget_1)
        self.checkBox_time.setGeometry(QtCore.QRect(170, 23, 21, 27))
        self.checkBox_time.setText("")
        self.checkBox_time.setObjectName("checkBox_time")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(-20, 10, 991, 751))
        self.widget1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget1.setStyleSheet("background-image: url(:/images/TonyPiUi.png);")
        self.widget1.setObjectName("widget1")
        self.widget_id1_2 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_2.setGeometry(QtCore.QRect(770, 570, 120, 80))
        self.widget_id1_2.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_2.setObjectName("widget_id1_2")
        self.label_ID1_2 = QtWidgets.QLabel(self.widget_id1_2)
        self.label_ID1_2.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_2.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_2.setFont(font)
        self.label_ID1_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_2.setObjectName("label_ID1_2")
        self.horizontalSlider_pulse_id2 = QtWidgets.QSlider(self.widget_id1_2)
        self.horizontalSlider_pulse_id2.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id2.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id2.setMinimum(0)
        self.horizontalSlider_pulse_id2.setMaximum(1000)
        self.horizontalSlider_pulse_id2.setPageStep(1)
        self.horizontalSlider_pulse_id2.setProperty("value", 500)
        self.horizontalSlider_pulse_id2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id2.setObjectName("horizontalSlider_pulse_id2")
        self.horizontalSlider_dev_id2 = QtWidgets.QSlider(self.widget_id1_2)
        self.horizontalSlider_dev_id2.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id2.setMinimum(-125)
        self.horizontalSlider_dev_id2.setMaximum(125)
        self.horizontalSlider_dev_id2.setPageStep(1)
        self.horizontalSlider_dev_id2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id2.setObjectName("horizontalSlider_dev_id2")
        self.label_id2 = QtWidgets.QLabel(self.widget_id1_2)
        self.label_id2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id2.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id2.setFont(font)
        self.label_id2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id2.setObjectName("label_id2")
        self.lineEdit_id2 = QtWidgets.QLineEdit(self.widget_id1_2)
        self.lineEdit_id2.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id2.sizePolicy().hasHeightForWidth())
        self.lineEdit_id2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id2.setFont(font)
        self.lineEdit_id2.setAutoFillBackground(False)
        self.lineEdit_id2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id2.setMaxLength(1000)
        self.lineEdit_id2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id2.setDragEnabled(False)
        self.lineEdit_id2.setReadOnly(False)
        self.lineEdit_id2.setObjectName("lineEdit_id2")
        self.widget_id1_3 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_3.setGeometry(QtCore.QRect(770, 480, 120, 80))
        self.widget_id1_3.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_3.setObjectName("widget_id1_3")
        self.label_ID1_4 = QtWidgets.QLabel(self.widget_id1_3)
        self.label_ID1_4.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_4.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_4.setFont(font)
        self.label_ID1_4.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_4.setObjectName("label_ID1_4")
        self.horizontalSlider_pulse_id3 = QtWidgets.QSlider(self.widget_id1_3)
        self.horizontalSlider_pulse_id3.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id3.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id3.setMinimum(0)
        self.horizontalSlider_pulse_id3.setMaximum(1000)
        self.horizontalSlider_pulse_id3.setPageStep(1)
        self.horizontalSlider_pulse_id3.setProperty("value", 500)
        self.horizontalSlider_pulse_id3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id3.setObjectName("horizontalSlider_pulse_id3")
        self.horizontalSlider_dev_id3 = QtWidgets.QSlider(self.widget_id1_3)
        self.horizontalSlider_dev_id3.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id3.setMinimum(-125)
        self.horizontalSlider_dev_id3.setMaximum(125)
        self.horizontalSlider_dev_id3.setPageStep(1)
        self.horizontalSlider_dev_id3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id3.setObjectName("horizontalSlider_dev_id3")
        self.label_id3 = QtWidgets.QLabel(self.widget_id1_3)
        self.label_id3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id3.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id3.setFont(font)
        self.label_id3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id3.setObjectName("label_id3")
        self.lineEdit_id3 = QtWidgets.QLineEdit(self.widget_id1_3)
        self.lineEdit_id3.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id3.sizePolicy().hasHeightForWidth())
        self.lineEdit_id3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id3.setFont(font)
        self.lineEdit_id3.setAutoFillBackground(False)
        self.lineEdit_id3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id3.setMaxLength(1000)
        self.lineEdit_id3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id3.setDragEnabled(False)
        self.lineEdit_id3.setReadOnly(False)
        self.lineEdit_id3.setObjectName("lineEdit_id3")
        self.widget_id1_4 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_4.setGeometry(QtCore.QRect(770, 390, 120, 80))
        self.widget_id1_4.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_4.setObjectName("widget_id1_4")
        self.label_ID1_5 = QtWidgets.QLabel(self.widget_id1_4)
        self.label_ID1_5.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_5.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_5.setFont(font)
        self.label_ID1_5.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_5.setObjectName("label_ID1_5")
        self.horizontalSlider_pulse_id4 = QtWidgets.QSlider(self.widget_id1_4)
        self.horizontalSlider_pulse_id4.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id4.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id4.setMinimum(0)
        self.horizontalSlider_pulse_id4.setMaximum(1000)
        self.horizontalSlider_pulse_id4.setPageStep(1)
        self.horizontalSlider_pulse_id4.setProperty("value", 500)
        self.horizontalSlider_pulse_id4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id4.setObjectName("horizontalSlider_pulse_id4")
        self.horizontalSlider_dev_id4 = QtWidgets.QSlider(self.widget_id1_4)
        self.horizontalSlider_dev_id4.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id4.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id4.setMinimum(-125)
        self.horizontalSlider_dev_id4.setMaximum(125)
        self.horizontalSlider_dev_id4.setPageStep(1)
        self.horizontalSlider_dev_id4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id4.setObjectName("horizontalSlider_dev_id4")
        self.label_id4 = QtWidgets.QLabel(self.widget_id1_4)
        self.label_id4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id4.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id4.setFont(font)
        self.label_id4.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id4.setObjectName("label_id4")
        self.lineEdit_id4 = QtWidgets.QLineEdit(self.widget_id1_4)
        self.lineEdit_id4.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id4.sizePolicy().hasHeightForWidth())
        self.lineEdit_id4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id4.setFont(font)
        self.lineEdit_id4.setAutoFillBackground(False)
        self.lineEdit_id4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id4.setMaxLength(1000)
        self.lineEdit_id4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id4.setDragEnabled(False)
        self.lineEdit_id4.setReadOnly(False)
        self.lineEdit_id4.setObjectName("lineEdit_id4")
        self.widget_id1_5 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_5.setGeometry(QtCore.QRect(725, 300, 120, 80))
        self.widget_id1_5.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_5.setObjectName("widget_id1_5")
        self.label_ID1_6 = QtWidgets.QLabel(self.widget_id1_5)
        self.label_ID1_6.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_6.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_6.setFont(font)
        self.label_ID1_6.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_6.setObjectName("label_ID1_6")
        self.horizontalSlider_pulse_id5 = QtWidgets.QSlider(self.widget_id1_5)
        self.horizontalSlider_pulse_id5.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id5.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id5.setMinimum(0)
        self.horizontalSlider_pulse_id5.setMaximum(1000)
        self.horizontalSlider_pulse_id5.setPageStep(1)
        self.horizontalSlider_pulse_id5.setProperty("value", 500)
        self.horizontalSlider_pulse_id5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id5.setObjectName("horizontalSlider_pulse_id5")
        self.horizontalSlider_dev_id5 = QtWidgets.QSlider(self.widget_id1_5)
        self.horizontalSlider_dev_id5.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id5.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id5.setMinimum(-125)
        self.horizontalSlider_dev_id5.setMaximum(125)
        self.horizontalSlider_dev_id5.setPageStep(1)
        self.horizontalSlider_dev_id5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id5.setObjectName("horizontalSlider_dev_id5")
        self.label_id5 = QtWidgets.QLabel(self.widget_id1_5)
        self.label_id5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id5.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id5.setFont(font)
        self.label_id5.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id5.setObjectName("label_id5")
        self.lineEdit_id5 = QtWidgets.QLineEdit(self.widget_id1_5)
        self.lineEdit_id5.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id5.sizePolicy().hasHeightForWidth())
        self.lineEdit_id5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id5.setFont(font)
        self.lineEdit_id5.setAutoFillBackground(False)
        self.lineEdit_id5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id5.setMaxLength(1000)
        self.lineEdit_id5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id5.setDragEnabled(False)
        self.lineEdit_id5.setReadOnly(False)
        self.lineEdit_id5.setObjectName("lineEdit_id5")
        self.widget_id1_6 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_6.setGeometry(QtCore.QRect(820, 190, 120, 80))
        self.widget_id1_6.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_6.setObjectName("widget_id1_6")
        self.label_ID1_7 = QtWidgets.QLabel(self.widget_id1_6)
        self.label_ID1_7.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_7.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_7.setFont(font)
        self.label_ID1_7.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_7.setObjectName("label_ID1_7")
        self.horizontalSlider_pulse_id6 = QtWidgets.QSlider(self.widget_id1_6)
        self.horizontalSlider_pulse_id6.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id6.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id6.setMinimum(0)
        self.horizontalSlider_pulse_id6.setMaximum(1000)
        self.horizontalSlider_pulse_id6.setPageStep(1)
        self.horizontalSlider_pulse_id6.setProperty("value", 500)
        self.horizontalSlider_pulse_id6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id6.setObjectName("horizontalSlider_pulse_id6")
        self.horizontalSlider_dev_id6 = QtWidgets.QSlider(self.widget_id1_6)
        self.horizontalSlider_dev_id6.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id6.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id6.setMinimum(-125)
        self.horizontalSlider_dev_id6.setMaximum(125)
        self.horizontalSlider_dev_id6.setPageStep(1)
        self.horizontalSlider_dev_id6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id6.setObjectName("horizontalSlider_dev_id6")
        self.label_id6 = QtWidgets.QLabel(self.widget_id1_6)
        self.label_id6.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id6.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id6.setFont(font)
        self.label_id6.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id6.setObjectName("label_id6")
        self.lineEdit_id6 = QtWidgets.QLineEdit(self.widget_id1_6)
        self.lineEdit_id6.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id6.sizePolicy().hasHeightForWidth())
        self.lineEdit_id6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id6.setFont(font)
        self.lineEdit_id6.setAutoFillBackground(False)
        self.lineEdit_id6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id6.setMaxLength(1000)
        self.lineEdit_id6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id6.setDragEnabled(False)
        self.lineEdit_id6.setReadOnly(False)
        self.lineEdit_id6.setObjectName("lineEdit_id6")
        self.widget_id1_7 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_7.setGeometry(QtCore.QRect(760, 100, 120, 80))
        self.widget_id1_7.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_7.setObjectName("widget_id1_7")
        self.label_ID1_8 = QtWidgets.QLabel(self.widget_id1_7)
        self.label_ID1_8.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_8.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_8.setFont(font)
        self.label_ID1_8.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_8.setObjectName("label_ID1_8")
        self.horizontalSlider_pulse_id7 = QtWidgets.QSlider(self.widget_id1_7)
        self.horizontalSlider_pulse_id7.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id7.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id7.setMinimum(0)
        self.horizontalSlider_pulse_id7.setMaximum(1000)
        self.horizontalSlider_pulse_id7.setPageStep(1)
        self.horizontalSlider_pulse_id7.setProperty("value", 500)
        self.horizontalSlider_pulse_id7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id7.setObjectName("horizontalSlider_pulse_id7")
        self.horizontalSlider_dev_id7 = QtWidgets.QSlider(self.widget_id1_7)
        self.horizontalSlider_dev_id7.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id7.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id7.setMinimum(-125)
        self.horizontalSlider_dev_id7.setMaximum(125)
        self.horizontalSlider_dev_id7.setPageStep(1)
        self.horizontalSlider_dev_id7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id7.setObjectName("horizontalSlider_dev_id7")
        self.label_id7 = QtWidgets.QLabel(self.widget_id1_7)
        self.label_id7.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id7.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id7.setFont(font)
        self.label_id7.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id7.setObjectName("label_id7")
        self.lineEdit_id7 = QtWidgets.QLineEdit(self.widget_id1_7)
        self.lineEdit_id7.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id7.sizePolicy().hasHeightForWidth())
        self.lineEdit_id7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id7.setFont(font)
        self.lineEdit_id7.setAutoFillBackground(False)
        self.lineEdit_id7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id7.setMaxLength(1000)
        self.lineEdit_id7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id7.setDragEnabled(False)
        self.lineEdit_id7.setReadOnly(False)
        self.lineEdit_id7.setObjectName("lineEdit_id7")
        self.widget_id1_8 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_8.setGeometry(QtCore.QRect(640, 30, 120, 80))
        self.widget_id1_8.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_8.setObjectName("widget_id1_8")
        self.label_ID1_9 = QtWidgets.QLabel(self.widget_id1_8)
        self.label_ID1_9.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_9.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_9.setFont(font)
        self.label_ID1_9.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_9.setObjectName("label_ID1_9")
        self.horizontalSlider_pulse_id8 = QtWidgets.QSlider(self.widget_id1_8)
        self.horizontalSlider_pulse_id8.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id8.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id8.setMinimum(0)
        self.horizontalSlider_pulse_id8.setMaximum(1000)
        self.horizontalSlider_pulse_id8.setPageStep(1)
        self.horizontalSlider_pulse_id8.setProperty("value", 500)
        self.horizontalSlider_pulse_id8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id8.setObjectName("horizontalSlider_pulse_id8")
        self.horizontalSlider_dev_id8 = QtWidgets.QSlider(self.widget_id1_8)
        self.horizontalSlider_dev_id8.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id8.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id8.setMinimum(-125)
        self.horizontalSlider_dev_id8.setMaximum(125)
        self.horizontalSlider_dev_id8.setPageStep(1)
        self.horizontalSlider_dev_id8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id8.setObjectName("horizontalSlider_dev_id8")
        self.label_id8 = QtWidgets.QLabel(self.widget_id1_8)
        self.label_id8.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id8.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id8.setFont(font)
        self.label_id8.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id8.setObjectName("label_id8")
        self.lineEdit_id8 = QtWidgets.QLineEdit(self.widget_id1_8)
        self.lineEdit_id8.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id8.sizePolicy().hasHeightForWidth())
        self.lineEdit_id8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id8.setFont(font)
        self.lineEdit_id8.setAutoFillBackground(False)
        self.lineEdit_id8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id8.setMaxLength(1000)
        self.lineEdit_id8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id8.setDragEnabled(False)
        self.lineEdit_id8.setReadOnly(False)
        self.lineEdit_id8.setObjectName("lineEdit_id8")
        self.widget_id1_9 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_9.setGeometry(QtCore.QRect(45, 660, 120, 80))
        self.widget_id1_9.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_9.setObjectName("widget_id1_9")
        self.label_ID1_10 = QtWidgets.QLabel(self.widget_id1_9)
        self.label_ID1_10.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_10.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_10.setFont(font)
        self.label_ID1_10.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_10.setObjectName("label_ID1_10")
        self.horizontalSlider_pulse_id9 = QtWidgets.QSlider(self.widget_id1_9)
        self.horizontalSlider_pulse_id9.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id9.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id9.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id9.setMinimum(0)
        self.horizontalSlider_pulse_id9.setMaximum(1000)
        self.horizontalSlider_pulse_id9.setPageStep(1)
        self.horizontalSlider_pulse_id9.setProperty("value", 500)
        self.horizontalSlider_pulse_id9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id9.setObjectName("horizontalSlider_pulse_id9")
        self.horizontalSlider_dev_id9 = QtWidgets.QSlider(self.widget_id1_9)
        self.horizontalSlider_dev_id9.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id9.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id9.setMinimum(-125)
        self.horizontalSlider_dev_id9.setMaximum(125)
        self.horizontalSlider_dev_id9.setPageStep(1)
        self.horizontalSlider_dev_id9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id9.setObjectName("horizontalSlider_dev_id9")
        self.label_id9 = QtWidgets.QLabel(self.widget_id1_9)
        self.label_id9.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id9.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id9.setFont(font)
        self.label_id9.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id9.setObjectName("label_id9")
        self.lineEdit_id9 = QtWidgets.QLineEdit(self.widget_id1_9)
        self.lineEdit_id9.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id9.sizePolicy().hasHeightForWidth())
        self.lineEdit_id9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id9.setFont(font)
        self.lineEdit_id9.setAutoFillBackground(False)
        self.lineEdit_id9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id9.setMaxLength(1000)
        self.lineEdit_id9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id9.setDragEnabled(False)
        self.lineEdit_id9.setReadOnly(False)
        self.lineEdit_id9.setObjectName("lineEdit_id9")
        self.widget_id1_10 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_10.setGeometry(QtCore.QRect(130, 570, 120, 80))
        self.widget_id1_10.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_10.setObjectName("widget_id1_10")
        self.label_ID1_11 = QtWidgets.QLabel(self.widget_id1_10)
        self.label_ID1_11.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_11.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_11.setFont(font)
        self.label_ID1_11.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_11.setObjectName("label_ID1_11")
        self.horizontalSlider_pulse_id10 = QtWidgets.QSlider(self.widget_id1_10)
        self.horizontalSlider_pulse_id10.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id10.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id10.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id10.setMinimum(0)
        self.horizontalSlider_pulse_id10.setMaximum(1000)
        self.horizontalSlider_pulse_id10.setPageStep(1)
        self.horizontalSlider_pulse_id10.setProperty("value", 500)
        self.horizontalSlider_pulse_id10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id10.setObjectName("horizontalSlider_pulse_id10")
        self.horizontalSlider_dev_id10 = QtWidgets.QSlider(self.widget_id1_10)
        self.horizontalSlider_dev_id10.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id10.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id10.setMinimum(-125)
        self.horizontalSlider_dev_id10.setMaximum(125)
        self.horizontalSlider_dev_id10.setPageStep(1)
        self.horizontalSlider_dev_id10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id10.setObjectName("horizontalSlider_dev_id10")
        self.label_id10 = QtWidgets.QLabel(self.widget_id1_10)
        self.label_id10.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id10.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id10.setFont(font)
        self.label_id10.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id10.setObjectName("label_id10")
        self.lineEdit_id10 = QtWidgets.QLineEdit(self.widget_id1_10)
        self.lineEdit_id10.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id10.sizePolicy().hasHeightForWidth())
        self.lineEdit_id10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id10.setFont(font)
        self.lineEdit_id10.setAutoFillBackground(False)
        self.lineEdit_id10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id10.setMaxLength(1000)
        self.lineEdit_id10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id10.setDragEnabled(False)
        self.lineEdit_id10.setReadOnly(False)
        self.lineEdit_id10.setObjectName("lineEdit_id10")
        self.widget_id1_11 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_11.setGeometry(QtCore.QRect(130, 480, 120, 80))
        self.widget_id1_11.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_11.setObjectName("widget_id1_11")
        self.label_ID1_12 = QtWidgets.QLabel(self.widget_id1_11)
        self.label_ID1_12.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_12.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_12.setFont(font)
        self.label_ID1_12.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_12.setObjectName("label_ID1_12")
        self.horizontalSlider_pulse_id11 = QtWidgets.QSlider(self.widget_id1_11)
        self.horizontalSlider_pulse_id11.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id11.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id11.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id11.setMinimum(0)
        self.horizontalSlider_pulse_id11.setMaximum(1000)
        self.horizontalSlider_pulse_id11.setPageStep(1)
        self.horizontalSlider_pulse_id11.setProperty("value", 500)
        self.horizontalSlider_pulse_id11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id11.setObjectName("horizontalSlider_pulse_id11")
        self.horizontalSlider_dev_id11 = QtWidgets.QSlider(self.widget_id1_11)
        self.horizontalSlider_dev_id11.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id11.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id11.setMinimum(-125)
        self.horizontalSlider_dev_id11.setMaximum(125)
        self.horizontalSlider_dev_id11.setPageStep(1)
        self.horizontalSlider_dev_id11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id11.setObjectName("horizontalSlider_dev_id11")
        self.label_id11 = QtWidgets.QLabel(self.widget_id1_11)
        self.label_id11.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id11.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id11.setFont(font)
        self.label_id11.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id11.setObjectName("label_id11")
        self.lineEdit_id11 = QtWidgets.QLineEdit(self.widget_id1_11)
        self.lineEdit_id11.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id11.sizePolicy().hasHeightForWidth())
        self.lineEdit_id11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id11.setFont(font)
        self.lineEdit_id11.setAutoFillBackground(False)
        self.lineEdit_id11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id11.setMaxLength(1000)
        self.lineEdit_id11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id11.setDragEnabled(False)
        self.lineEdit_id11.setReadOnly(False)
        self.lineEdit_id11.setObjectName("lineEdit_id11")
        self.widget_id1_12 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_12.setGeometry(QtCore.QRect(130, 390, 120, 80))
        self.widget_id1_12.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_12.setObjectName("widget_id1_12")
        self.label_ID1_13 = QtWidgets.QLabel(self.widget_id1_12)
        self.label_ID1_13.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_13.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_13.setFont(font)
        self.label_ID1_13.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_13.setObjectName("label_ID1_13")
        self.horizontalSlider_pulse_id12 = QtWidgets.QSlider(self.widget_id1_12)
        self.horizontalSlider_pulse_id12.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id12.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id12.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id12.setMinimum(0)
        self.horizontalSlider_pulse_id12.setMaximum(1000)
        self.horizontalSlider_pulse_id12.setPageStep(1)
        self.horizontalSlider_pulse_id12.setProperty("value", 500)
        self.horizontalSlider_pulse_id12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id12.setObjectName("horizontalSlider_pulse_id12")
        self.horizontalSlider_dev_id12 = QtWidgets.QSlider(self.widget_id1_12)
        self.horizontalSlider_dev_id12.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id12.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id12.setMinimum(-125)
        self.horizontalSlider_dev_id12.setMaximum(125)
        self.horizontalSlider_dev_id12.setPageStep(1)
        self.horizontalSlider_dev_id12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id12.setObjectName("horizontalSlider_dev_id12")
        self.label_id12 = QtWidgets.QLabel(self.widget_id1_12)
        self.label_id12.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id12.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id12.setFont(font)
        self.label_id12.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id12.setObjectName("label_id12")
        self.lineEdit_id12 = QtWidgets.QLineEdit(self.widget_id1_12)
        self.lineEdit_id12.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id12.sizePolicy().hasHeightForWidth())
        self.lineEdit_id12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id12.setFont(font)
        self.lineEdit_id12.setAutoFillBackground(False)
        self.lineEdit_id12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id12.setMaxLength(1000)
        self.lineEdit_id12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id12.setDragEnabled(False)
        self.lineEdit_id12.setReadOnly(False)
        self.lineEdit_id12.setObjectName("lineEdit_id12")
        self.widget_id1_13 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_13.setGeometry(QtCore.QRect(180, 300, 120, 80))
        self.widget_id1_13.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_13.setObjectName("widget_id1_13")
        self.label_ID1_14 = QtWidgets.QLabel(self.widget_id1_13)
        self.label_ID1_14.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_14.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_14.setFont(font)
        self.label_ID1_14.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_14.setObjectName("label_ID1_14")
        self.horizontalSlider_pulse_id13 = QtWidgets.QSlider(self.widget_id1_13)
        self.horizontalSlider_pulse_id13.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id13.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id13.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id13.setMinimum(0)
        self.horizontalSlider_pulse_id13.setMaximum(1000)
        self.horizontalSlider_pulse_id13.setPageStep(1)
        self.horizontalSlider_pulse_id13.setProperty("value", 500)
        self.horizontalSlider_pulse_id13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id13.setObjectName("horizontalSlider_pulse_id13")
        self.horizontalSlider_dev_id13 = QtWidgets.QSlider(self.widget_id1_13)
        self.horizontalSlider_dev_id13.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id13.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id13.setMinimum(-125)
        self.horizontalSlider_dev_id13.setMaximum(125)
        self.horizontalSlider_dev_id13.setPageStep(1)
        self.horizontalSlider_dev_id13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id13.setObjectName("horizontalSlider_dev_id13")
        self.label_id13 = QtWidgets.QLabel(self.widget_id1_13)
        self.label_id13.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id13.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id13.setFont(font)
        self.label_id13.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id13.setObjectName("label_id13")
        self.lineEdit_id13 = QtWidgets.QLineEdit(self.widget_id1_13)
        self.lineEdit_id13.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id13.sizePolicy().hasHeightForWidth())
        self.lineEdit_id13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id13.setFont(font)
        self.lineEdit_id13.setAutoFillBackground(False)
        self.lineEdit_id13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id13.setMaxLength(1000)
        self.lineEdit_id13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id13.setDragEnabled(False)
        self.lineEdit_id13.setReadOnly(False)
        self.lineEdit_id13.setObjectName("lineEdit_id13")
        self.widget_id1_14 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_14.setGeometry(QtCore.QRect(80, 190, 120, 80))
        self.widget_id1_14.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_14.setObjectName("widget_id1_14")
        self.label_ID1_15 = QtWidgets.QLabel(self.widget_id1_14)
        self.label_ID1_15.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_15.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_15.setFont(font)
        self.label_ID1_15.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_15.setObjectName("label_ID1_15")
        self.horizontalSlider_pulse_id14 = QtWidgets.QSlider(self.widget_id1_14)
        self.horizontalSlider_pulse_id14.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id14.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id14.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id14.setMinimum(0)
        self.horizontalSlider_pulse_id14.setMaximum(1000)
        self.horizontalSlider_pulse_id14.setPageStep(1)
        self.horizontalSlider_pulse_id14.setProperty("value", 500)
        self.horizontalSlider_pulse_id14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id14.setObjectName("horizontalSlider_pulse_id14")
        self.horizontalSlider_dev_id14 = QtWidgets.QSlider(self.widget_id1_14)
        self.horizontalSlider_dev_id14.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id14.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id14.setMinimum(-125)
        self.horizontalSlider_dev_id14.setMaximum(125)
        self.horizontalSlider_dev_id14.setPageStep(1)
        self.horizontalSlider_dev_id14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id14.setObjectName("horizontalSlider_dev_id14")
        self.label_id14 = QtWidgets.QLabel(self.widget_id1_14)
        self.label_id14.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id14.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id14.setFont(font)
        self.label_id14.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id14.setObjectName("label_id14")
        self.lineEdit_id14 = QtWidgets.QLineEdit(self.widget_id1_14)
        self.lineEdit_id14.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id14.sizePolicy().hasHeightForWidth())
        self.lineEdit_id14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id14.setFont(font)
        self.lineEdit_id14.setAutoFillBackground(False)
        self.lineEdit_id14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id14.setMaxLength(1000)
        self.lineEdit_id14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id14.setDragEnabled(False)
        self.lineEdit_id14.setReadOnly(False)
        self.lineEdit_id14.setObjectName("lineEdit_id14")
        self.widget_id1_15 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_15.setGeometry(QtCore.QRect(140, 100, 120, 80))
        self.widget_id1_15.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_15.setObjectName("widget_id1_15")
        self.label_ID1_16 = QtWidgets.QLabel(self.widget_id1_15)
        self.label_ID1_16.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_16.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_16.setFont(font)
        self.label_ID1_16.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_16.setObjectName("label_ID1_16")
        self.horizontalSlider_pulse_id15 = QtWidgets.QSlider(self.widget_id1_15)
        self.horizontalSlider_pulse_id15.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id15.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id15.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id15.setMinimum(0)
        self.horizontalSlider_pulse_id15.setMaximum(1000)
        self.horizontalSlider_pulse_id15.setPageStep(1)
        self.horizontalSlider_pulse_id15.setProperty("value", 500)
        self.horizontalSlider_pulse_id15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id15.setObjectName("horizontalSlider_pulse_id15")
        self.horizontalSlider_dev_id15 = QtWidgets.QSlider(self.widget_id1_15)
        self.horizontalSlider_dev_id15.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id15.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id15.setMinimum(-125)
        self.horizontalSlider_dev_id15.setMaximum(125)
        self.horizontalSlider_dev_id15.setPageStep(1)
        self.horizontalSlider_dev_id15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id15.setObjectName("horizontalSlider_dev_id15")
        self.label_id15 = QtWidgets.QLabel(self.widget_id1_15)
        self.label_id15.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id15.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id15.setFont(font)
        self.label_id15.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id15.setObjectName("label_id15")
        self.lineEdit_id15 = QtWidgets.QLineEdit(self.widget_id1_15)
        self.lineEdit_id15.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id15.sizePolicy().hasHeightForWidth())
        self.lineEdit_id15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id15.setFont(font)
        self.lineEdit_id15.setAutoFillBackground(False)
        self.lineEdit_id15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id15.setMaxLength(1000)
        self.lineEdit_id15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id15.setDragEnabled(False)
        self.lineEdit_id15.setReadOnly(False)
        self.lineEdit_id15.setObjectName("lineEdit_id15")
        self.widget_id1_16 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_16.setGeometry(QtCore.QRect(260, 30, 120, 80))
        self.widget_id1_16.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_16.setObjectName("widget_id1_16")
        self.label_ID1_17 = QtWidgets.QLabel(self.widget_id1_16)
        self.label_ID1_17.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_17.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_17.setFont(font)
        self.label_ID1_17.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_17.setObjectName("label_ID1_17")
        self.horizontalSlider_pulse_id16 = QtWidgets.QSlider(self.widget_id1_16)
        self.horizontalSlider_pulse_id16.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id16.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id16.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id16.setMinimum(0)
        self.horizontalSlider_pulse_id16.setMaximum(1000)
        self.horizontalSlider_pulse_id16.setPageStep(1)
        self.horizontalSlider_pulse_id16.setProperty("value", 500)
        self.horizontalSlider_pulse_id16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id16.setObjectName("horizontalSlider_pulse_id16")
        self.horizontalSlider_dev_id16 = QtWidgets.QSlider(self.widget_id1_16)
        self.horizontalSlider_dev_id16.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id16.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id16.setMinimum(-125)
        self.horizontalSlider_dev_id16.setMaximum(125)
        self.horizontalSlider_dev_id16.setPageStep(1)
        self.horizontalSlider_dev_id16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id16.setObjectName("horizontalSlider_dev_id16")
        self.label_id16 = QtWidgets.QLabel(self.widget_id1_16)
        self.label_id16.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id16.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id16.setFont(font)
        self.label_id16.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id16.setObjectName("label_id16")
        self.lineEdit_id16 = QtWidgets.QLineEdit(self.widget_id1_16)
        self.lineEdit_id16.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id16.sizePolicy().hasHeightForWidth())
        self.lineEdit_id16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id16.setFont(font)
        self.lineEdit_id16.setAutoFillBackground(False)
        self.lineEdit_id16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id16.setMaxLength(1000)
        self.lineEdit_id16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id16.setDragEnabled(False)
        self.lineEdit_id16.setReadOnly(False)
        self.lineEdit_id16.setObjectName("lineEdit_id16")
        self.layoutWidget = QtWidgets.QWidget(self.widget1)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 0, 85, 62))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_zn = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_zn.setObjectName("radioButton_zn")
        self.verticalLayout.addWidget(self.radioButton_zn)
        self.radioButton_en = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_en.setObjectName("radioButton_en")
        self.verticalLayout.addWidget(self.radioButton_en)
        self.widget_id1 = QtWidgets.QWidget(self.widget1)
        self.widget_id1.setGeometry(QtCore.QRect(830, 660, 120, 80))
        self.widget_id1.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1.setObjectName("widget_id1")
        self.label_ID1 = QtWidgets.QLabel(self.widget_id1)
        self.label_ID1.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1.setFont(font)
        self.label_ID1.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1.setObjectName("label_ID1")
        self.horizontalSlider_pulse_id1 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_pulse_id1.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id1.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id1.setMinimum(0)
        self.horizontalSlider_pulse_id1.setMaximum(1000)
        self.horizontalSlider_pulse_id1.setPageStep(1)
        self.horizontalSlider_pulse_id1.setProperty("value", 500)
        self.horizontalSlider_pulse_id1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id1.setObjectName("horizontalSlider_pulse_id1")
        self.horizontalSlider_dev_id1 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_dev_id1.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id1.setMinimum(-125)
        self.horizontalSlider_dev_id1.setMaximum(125)
        self.horizontalSlider_dev_id1.setPageStep(1)
        self.horizontalSlider_dev_id1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id1.setObjectName("horizontalSlider_dev_id1")
        self.label_id1 = QtWidgets.QLabel(self.widget_id1)
        self.label_id1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id1.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id1.setFont(font)
        self.label_id1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id1.setObjectName("label_id1")
        self.lineEdit_id1 = QtWidgets.QLineEdit(self.widget_id1)
        self.lineEdit_id1.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id1.sizePolicy().hasHeightForWidth())
        self.lineEdit_id1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id1.setFont(font)
        self.lineEdit_id1.setAutoFillBackground(False)
        self.lineEdit_id1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id1.setMaxLength(1000)
        self.lineEdit_id1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id1.setDragEnabled(False)
        self.lineEdit_id1.setReadOnly(False)
        self.lineEdit_id1.setObjectName("lineEdit_id1")
        self.widget_id1_17 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_17.setGeometry(QtCore.QRect(30, 280, 120, 80))
        self.widget_id1_17.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_17.setObjectName("widget_id1_17")
        self.label_ID1_18 = QtWidgets.QLabel(self.widget_id1_17)
        self.label_ID1_18.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_18.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_18.setFont(font)
        self.label_ID1_18.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_18.setObjectName("label_ID1_18")
        self.horizontalSlider_pulse_id17 = QtWidgets.QSlider(self.widget_id1_17)
        self.horizontalSlider_pulse_id17.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id17.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id17.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id17.setMinimum(0)
        self.horizontalSlider_pulse_id17.setMaximum(1000)
        self.horizontalSlider_pulse_id17.setPageStep(1)
        self.horizontalSlider_pulse_id17.setProperty("value", 500)
        self.horizontalSlider_pulse_id17.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id17.setObjectName("horizontalSlider_pulse_id17")
        self.horizontalSlider_dev_id17 = QtWidgets.QSlider(self.widget_id1_17)
        self.horizontalSlider_dev_id17.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id17.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id17.setMinimum(-125)
        self.horizontalSlider_dev_id17.setMaximum(125)
        self.horizontalSlider_dev_id17.setPageStep(1)
        self.horizontalSlider_dev_id17.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id17.setObjectName("horizontalSlider_dev_id17")
        self.label_id17 = QtWidgets.QLabel(self.widget_id1_17)
        self.label_id17.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id17.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id17.setFont(font)
        self.label_id17.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id17.setObjectName("label_id17")
        self.lineEdit_id17 = QtWidgets.QLineEdit(self.widget_id1_17)
        self.lineEdit_id17.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id17.sizePolicy().hasHeightForWidth())
        self.lineEdit_id17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id17.setFont(font)
        self.lineEdit_id17.setAutoFillBackground(False)
        self.lineEdit_id17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id17.setMaxLength(1000)
        self.lineEdit_id17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id17.setDragEnabled(False)
        self.lineEdit_id17.setReadOnly(False)
        self.lineEdit_id17.setObjectName("lineEdit_id17")
        self.widget_id1_18 = QtWidgets.QWidget(self.widget1)
        self.widget_id1_18.setGeometry(QtCore.QRect(870, 280, 120, 80))
        self.widget_id1_18.setStyleSheet("background-color: rgb(255, 170, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1_18.setObjectName("widget_id1_18")
        self.label_ID1_19 = QtWidgets.QLabel(self.widget_id1_18)
        self.label_ID1_19.setGeometry(QtCore.QRect(40, 0, 45, 16))
        self.label_ID1_19.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1_19.setFont(font)
        self.label_ID1_19.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID1_19.setObjectName("label_ID1_19")
        self.horizontalSlider_pulse_id18 = QtWidgets.QSlider(self.widget_id1_18)
        self.horizontalSlider_pulse_id18.setGeometry(QtCore.QRect(20, 20, 83, 16))
        self.horizontalSlider_pulse_id18.setAutoFillBackground(False)
        self.horizontalSlider_pulse_id18.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_pulse_id18.setMinimum(0)
        self.horizontalSlider_pulse_id18.setMaximum(1000)
        self.horizontalSlider_pulse_id18.setPageStep(1)
        self.horizontalSlider_pulse_id18.setProperty("value", 500)
        self.horizontalSlider_pulse_id18.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_id18.setObjectName("horizontalSlider_pulse_id18")
        self.horizontalSlider_dev_id18 = QtWidgets.QSlider(self.widget_id1_18)
        self.horizontalSlider_dev_id18.setGeometry(QtCore.QRect(40, 60, 45, 18))
        self.horizontalSlider_dev_id18.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_id18.setMinimum(-125)
        self.horizontalSlider_dev_id18.setMaximum(125)
        self.horizontalSlider_dev_id18.setPageStep(1)
        self.horizontalSlider_dev_id18.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_id18.setObjectName("horizontalSlider_dev_id18")
        self.label_id18 = QtWidgets.QLabel(self.widget_id1_18)
        self.label_id18.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.label_id18.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_id18.setFont(font)
        self.label_id18.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_id18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id18.setObjectName("label_id18")
        self.lineEdit_id18 = QtWidgets.QLineEdit(self.widget_id1_18)
        self.lineEdit_id18.setGeometry(QtCore.QRect(40, 40, 45, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id18.sizePolicy().hasHeightForWidth())
        self.lineEdit_id18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_id18.setFont(font)
        self.lineEdit_id18.setAutoFillBackground(False)
        self.lineEdit_id18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_id18.setMaxLength(1000)
        self.lineEdit_id18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_id18.setDragEnabled(False)
        self.lineEdit_id18.setReadOnly(False)
        self.lineEdit_id18.setObjectName("lineEdit_id18")
        self.HandEnabled = QtWidgets.QCheckBox(self.widget1)
        self.HandEnabled.setEnabled(True)
        self.HandEnabled.setGeometry(QtCore.QRect(50, 65, 91, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.HandEnabled.setFont(font)
        self.HandEnabled.setObjectName("HandEnabled")
        self.widget_id1_18.raise_()
        self.widget_id1_2.raise_()
        self.widget_id1_3.raise_()
        self.widget_id1_4.raise_()
        self.widget_id1_5.raise_()
        self.widget_id1_6.raise_()
        self.widget_id1_7.raise_()
        self.widget_id1_8.raise_()
        self.widget_id1_9.raise_()
        self.widget_id1_10.raise_()
        self.widget_id1_11.raise_()
        self.widget_id1_12.raise_()
        self.widget_id1_13.raise_()
        self.widget_id1_14.raise_()
        self.widget_id1_15.raise_()
        self.widget_id1_16.raise_()
        self.layoutWidget.raise_()
        self.widget_id1.raise_()
        self.widget_id1_17.raise_()
        self.HandEnabled.raise_()
        self.label_action_number = QtWidgets.QLabel(self.widget)
        self.label_action_number.setGeometry(QtCore.QRect(980, 420, 480, 22))
        self.label_action_number.setText("")
        self.label_action_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_action_number.setObjectName("label_action_number")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TonyPi 1.20"))
        self.label_action.setText(_translate("Form", "动作组"))
        self.Button_DelectSingle.setText(_translate("Form", "单个擦除"))
        self.Button_AllDelect.setText(_translate("Form", "全部擦除"))
        self.Button_RunAction.setText(_translate("Form", "动作运行"))
        self.Button_StopAction.setText(_translate("Form", "动作停止"))
        self.checkBox.setText(_translate("Form", "循环"))
        self.Button_Run.setText(_translate("Form", "运行"))
        self.Button_ReadDeviation.setText(_translate("Form", "读取偏差"))
        self.Button_DownloadDeviation.setText(_translate("Form", "下载偏差"))
        self.Button_ReSetServos.setText(_translate("Form", "舵机回中"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Index"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ID:1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "ID:2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "ID:3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "ID:4"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "ID:5"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "ID:6"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "ID:7"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "ID:8"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Form", "ID:9"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Form", "ID:10"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Form", "ID:11"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("Form", "ID:12"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("Form", "ID:13"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("Form", "ID:14"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("Form", "ID:15"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("Form", "ID:16"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("Form", "ID:17"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("Form", "ID:18"))
        self.Button_OpenActionGroup.setText(_translate("Form", "打开动作文件"))
        self.Button_SaveActionGroup.setText(_translate("Form", "保存动作文件"))
        self.Button_TandemActionGroup.setText(_translate("Form", "串联动作文件"))
        self.label_time.setText(_translate("Form", "时间"))
        self.lineEdit_time.setText(_translate("Form", "1000"))
        self.Button_AddAction.setText(_translate("Form", "添加动作"))
        self.Button_DelectAction.setText(_translate("Form", "删除动作"))
        self.Button_UpdateAction.setText(_translate("Form", "更新动作"))
        self.Button_InsertAction.setText(_translate("Form", "插入动作"))
        self.Button_ServoPowerDown.setText(_translate("Form", "手掰编程"))
        self.Button_AngularReadback.setText(_translate("Form", "角度回读"))
        self.Button_MoveUpAction.setText(_translate("Form", "上移动作"))
        self.Button_MoveDownAction.setText(_translate("Form", "下移动作"))
        self.label_total_time.setText(_translate("Form", "运行总时间"))
        self.label.setText(_translate("Form", "ms"))
        self.label_5.setText(_translate("Form", "s"))
        self.label_TotalTime.setText(_translate("Form", "0.0"))
        self.label_ID1_2.setText(_translate("Form", "ID:2"))
        self.label_id2.setText(_translate("Form", "0"))
        self.lineEdit_id2.setText(_translate("Form", "500"))
        self.label_ID1_4.setText(_translate("Form", "ID:3"))
        self.label_id3.setText(_translate("Form", "0"))
        self.lineEdit_id3.setText(_translate("Form", "500"))
        self.label_ID1_5.setText(_translate("Form", "ID:4"))
        self.label_id4.setText(_translate("Form", "0"))
        self.lineEdit_id4.setText(_translate("Form", "500"))
        self.label_ID1_6.setText(_translate("Form", "ID:5"))
        self.label_id5.setText(_translate("Form", "0"))
        self.lineEdit_id5.setText(_translate("Form", "500"))
        self.label_ID1_7.setText(_translate("Form", "ID:6"))
        self.label_id6.setText(_translate("Form", "0"))
        self.lineEdit_id6.setText(_translate("Form", "500"))
        self.label_ID1_8.setText(_translate("Form", "ID:7"))
        self.label_id7.setText(_translate("Form", "0"))
        self.lineEdit_id7.setText(_translate("Form", "500"))
        self.label_ID1_9.setText(_translate("Form", "ID:8"))
        self.label_id8.setText(_translate("Form", "0"))
        self.lineEdit_id8.setText(_translate("Form", "500"))
        self.label_ID1_10.setText(_translate("Form", "ID:9"))
        self.label_id9.setText(_translate("Form", "0"))
        self.lineEdit_id9.setText(_translate("Form", "500"))
        self.label_ID1_11.setText(_translate("Form", "ID:10"))
        self.label_id10.setText(_translate("Form", "0"))
        self.lineEdit_id10.setText(_translate("Form", "500"))
        self.label_ID1_12.setText(_translate("Form", "ID:11"))
        self.label_id11.setText(_translate("Form", "0"))
        self.lineEdit_id11.setText(_translate("Form", "500"))
        self.label_ID1_13.setText(_translate("Form", "ID:12"))
        self.label_id12.setText(_translate("Form", "0"))
        self.lineEdit_id12.setText(_translate("Form", "500"))
        self.label_ID1_14.setText(_translate("Form", "ID:13"))
        self.label_id13.setText(_translate("Form", "0"))
        self.lineEdit_id13.setText(_translate("Form", "500"))
        self.label_ID1_15.setText(_translate("Form", "ID:14"))
        self.label_id14.setText(_translate("Form", "0"))
        self.lineEdit_id14.setText(_translate("Form", "500"))
        self.label_ID1_16.setText(_translate("Form", "ID:15"))
        self.label_id15.setText(_translate("Form", "0"))
        self.lineEdit_id15.setText(_translate("Form", "500"))
        self.label_ID1_17.setText(_translate("Form", "ID:16"))
        self.label_id16.setText(_translate("Form", "0"))
        self.lineEdit_id16.setText(_translate("Form", "500"))
        self.radioButton_zn.setText(_translate("Form", "中文"))
        self.radioButton_en.setText(_translate("Form", "English"))
        self.label_ID1.setText(_translate("Form", "ID:1"))
        self.label_id1.setText(_translate("Form", "0"))
        self.lineEdit_id1.setText(_translate("Form", "500"))
        self.label_ID1_18.setText(_translate("Form", "ID:17"))
        self.label_id17.setText(_translate("Form", "0"))
        self.lineEdit_id17.setText(_translate("Form", "500"))
        self.label_ID1_19.setText(_translate("Form", "ID:18"))
        self.label_id18.setText(_translate("Form", "0"))
        self.lineEdit_id18.setText(_translate("Form", "500"))
        self.HandEnabled.setText(_translate("Form", "开合手掌"))

import resource_rc
