spin_manifest_version = 2

[application]
authors = ["award40"]
description = ""
name = "example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "example"

[component.example]
source = "_output/app.wasm"
[component.example.build]
command = "componentize-py -w spin-http componentize app -o _output/app.wasm"
watch = ["*.py", "requirements.txt"]
